# Generated by Django 2.1 on 2018-09-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customlogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaselog',
            options={'ordering': ('-publishing_date',)},
        ),
    ]
