sudo: required
dist: trusty
language: python
matrix:
  include:
  - language: python
    python: 3.6
    cache: pip
    before_install: cd happykh
    install:
    - pip install -r requirements.txt
    services:
    - postgresql
    addons:
      postgresql: '9.5'
    before_script:
    - psql -U postgres -c "CREATE DATABASE happykh;"
    - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres
    - psql -c "ALTER ROLE admin SET client_encoding TO 'utf8';" -U postgres
    - psql -c "ALTER ROLE admin SET default_transaction_isolation TO 'read committed';" -U postgres
    - psql -c "ALTER ROLE admin SET timezone TO 'UTC';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE happykh TO admin;" -U postgres
    - psql -c "ALTER USER admin CREATEDB;" -U postgres
    - python3 manage.py migrate
    script:
    - pytest
    - pylint users
    - pylint tests
    - pylint places


  - language: node_js
    node_js: 8.12.0
    cache:
      directories:
      - node_modules
    addons:
      chrome: stable
    before_install: cd frontend
    install:
    - npm install
    script:
    - npm run lint
    - npm run test:unit