sudo: required
dist: trusty
language: python
matrix:
  include:
  - language: python
    python: 3.6
    cache: pip
    before_install: cd backend
    install:
    - pip install -r requirements.txt
    services:
    - postgresql
    addons:
      postgresql: '9.5'
    before_script:
    - psql -U postgres -c "CREATE DATABASE happykh;"
    - psql -c "CREATE USER $db_user WITH PASSWORD '$db_password';" -U postgres
    - psql -c "ALTER ROLE $db_user SET client_encoding TO 'utf8';" -U postgres
    - psql -c "ALTER ROLE $db_user SET default_transaction_isolation TO 'read committed';"
      -U postgres
    - psql -c "ALTER ROLE $db_user SET timezone TO 'UTC';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE happykh TO $db_user;" -U postgres
    - psql -c "ALTER USER $db_user CREATEDB;" -U postgres
    - python3 manage.py migrate
    script:
    - pytest
    - pylint --load-plugins pylint_django users
    - pylint --load-plugins pylint_django places
    - pylint --load-plugins pylint_django tests
    - codecov --token=$CODECOV_TOKEN
  - language: node_js
    node_js: 8.12.0
    cache:
      directories:
      - node_modules
    addons:
      chrome: stable
    before_install: cd frontend
    install:
    - npm install
    script:
    - npm run lint
    - npm run test:unit
