# Generated by Django 2.1 on 2018-09-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customlogger', '0002_auto_20180917_0801'),
        ('customlogger', '0002_auto_20180914_1239'),
    ]

    operations = [
    ]
