# Generated by Django 2.1.2 on 2018-10-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import places.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('address', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', stdimage.models.StdImageField(blank=True, default='', null=True, upload_to=places.models.Place._make_upload_logo)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Address')),
                ('edit_permitted_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
