# Generated by Django 2.1.2 on 2018-11-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20181101_1451'),
        ('places', '0002_place_created'),
    ]

    operations = [
    ]
