# Generated by Django 2.1.2 on 2018-11-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_commentplace_edited'),
        ('places', '0006_auto_20181117_1714'),
    ]

    operations = [
    ]
