"""
Django settings for happykh project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .base import *

FRONT_URL_PREFIX = 'http://18.223.185.163/#/'
ALLOWED_HOSTS = ['18.223.185.163']

DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'happykh',
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '',
    }
}

CORS_ORIGIN_REGEX_WHITELIST = (
    # For Client
    r'http://localhost*',
    r'http://127.0.0.1:*',
    r'http://18.223.185.163:*'
)
