# Generated by Django 2.1.2 on 2018-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
