# Generated by Django 2.1 on 2018-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0002_auto_20181002_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
