# Generated by Django 2.1.2 on 2018-11-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_merge_20181102_1530'),
        ('places', '0003_merge_20181104_1243'),
    ]

    operations = [
    ]
