# Generated by Django 2.1 on 2018-10-09 12:17

from django.db import migrations
import places.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20181004_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, default='', null=True, upload_to=places.models.Place._make_upload_logo),
        ),
    ]
