# Generated by Django 2.1.2 on 2018-10-07 07:16

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0003_auto_20181004_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True,
                                    upload_to=places.models.make_upload_logo),
        ),
    ]
