# Generated by Django 2.1.2 on 2018-10-08 21:00

from django.db import migrations
import places.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20181007_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, default='', null=True, upload_to=places.models.make_upload_logo),
        ),
    ]
