# Generated by Django 2.1.2 on 2018-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentplace',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
