# Generated by Django 2.1.2 on 2018-10-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Address'),
        ),
    ]
