# Generated by Django 2.1.2 on 2018-11-17 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0005_placerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.AddField(
            model_name='place',
            name='edit_permitted_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
