# Generated by Django 2.1 on 2018-10-02 12:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180928_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='user/profile_image/b/l/blank-profile-picture.png', upload_to=users.models.User.make_upload_profile_image),
        ),
    ]
