# Generated by Django 2.1 on 2018-10-05 14:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181002_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=users.models.User.make_upload_profile_image),
        ),
    ]
