# Generated by Django 2.1.2 on 2018-10-07 07:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_merge_20181002_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(
                blank=True, default='', null=True,
                upload_to=users.models.make_upload_profile_image),
        ),
    ]
