# Generated by Django 2.1.2 on 2018-10-08 21:00

from django.db import migrations
import stdimage.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181007_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=stdimage.models.StdImageField(blank=True, default='', null=True, upload_to=users.models.make_upload_profile_image),
        ),
    ]
