# Generated by Django 2.1 on 2018-10-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181005_1405'),
        ('users', '0005_merge_20181002_1725'),
    ]

    operations = [
    ]
